<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Rental Mobil</name>
   <tag></tag>
   <elementGuidId>54da3c3d-ed84-430b-a8a9-a2963e221ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/a[6]/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-4rbku5.r-1awozwy.r-2lfw2k.r-kdyh1x.r-6koalj.r-88pszg.r-1p6iasa.r-1pn2ns4 > h4.css-4rbku5.css-901oao.r-jwli3a.r-t1w4ow.r-1b43r93.r-b88u0q.r-1cwl3u0.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>8514598c-3a41-4871-9de0-7a44652ee1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a5c46d30-cbd9-4fe7-87ef-a72e6cc71e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9c642a8a-7f11-47eb-a93f-e67aab97fe8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>b17ecf9d-0bb6-4f40-a20a-8554781755b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-b88u0q r-1cwl3u0 r-fdjqy7</value>
      <webElementGuid>6d01c8c6-b4f6-4182-8790-9c9c1bf5f71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rental Mobil</value>
      <webElementGuid>a6a0205f-9066-461c-9482-ee68f6f54668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-bztko3 r-ipm5af r-iy1yoi r-13qz1uu r-8ny0jo&quot;]/div[@class=&quot;css-1dbjc4n r-wy61xf r-1jgb5lz r-r0h9e2 r-u8s1d r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1niwhzg r-1777fci r-10gryf7 r-82yag r-u8s1d r-iy1yoi r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-qklmqi r-1dppl8s r-5kkj8d r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-6koalj r-1ugchlj r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-tzz3ar r-1pi2tsx r-1ktosi0 r-mrxtjd r-s1qlax r-13qz1uu&quot;]/a[@class=&quot;css-4rbku5 r-1awozwy r-2lfw2k r-kdyh1x r-6koalj r-88pszg r-1p6iasa r-1pn2ns4&quot;]/h4[@class=&quot;css-4rbku5 css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-b88u0q r-1cwl3u0 r-fdjqy7&quot;]</value>
      <webElementGuid>1f35cf18-c3eb-4130-8ab6-74b0f7bc52a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/a[6]/h4</value>
      <webElementGuid>7611aeee-b50e-478d-a026-61bdbd644e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antar Jemput Bandara'])[1]/following::h4[1]</value>
      <webElementGuid>4dc334ea-ef94-41e5-84e7-31c308d6f329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiket Bus &amp; Travel'])[1]/following::h4[2]</value>
      <webElementGuid>bb9dddda-8445-4c7e-b038-fe1b62d2c991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atraksi dan Aktivitas'])[1]/preceding::h4[1]</value>
      <webElementGuid>8230a47b-7601-4611-8db6-10444a1492a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Lainnya'])[1]/preceding::h4[2]</value>
      <webElementGuid>865146fa-2412-4bd7-8055-eed20f8a85ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rental Mobil']/parent::*</value>
      <webElementGuid>13665ff8-d6ad-4b81-99b1-79dcd80e9cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/h4</value>
      <webElementGuid>ad1dad98-1973-4cf3-ae10-0efff7bf9021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Rental Mobil' or . = 'Rental Mobil')]</value>
      <webElementGuid>a22743cb-8fe7-4cae-b93b-02e897b7f114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
